const mongoose = require('mongoose');

const ReportSchema = new mongoose.Schema({
    userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    timeframe: { type: String, required: true }, // e.g., "January 2026"
    insightSummary: { type: String }, // Generated by Gemini AI
    content: { type: Object } // Structured data for PDF/CSV generation
}, { timestamps: true });

module.exports = mongoose.model('Report', ReportSchema);